[package]
name = "validators-app-api"
version = "0.1.0"
authors = ["Konstantin Stepanov <konstantin.s@p2p.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.64"
serde_derive = "1.0.126"
serde = "1.0.126"
log = "0.4.14"
reqwest = { version = "0.11.3", features = ["blocking", "rustls-tls", "json"] }
